rollno=[1,2,3,4,5]
names=["Jenny","Akshith","Ram"]
list=[1,"jenny",True,10.10]#all datatyeps allowed in list
print(rollno)
nos=[1,2,3,4,5]
print(nos[1:2])
print(nos[:6:2])
n=[2,4,3,1,0,9]
n.sort()
print(n)
n.reverse()
print(n)
print(min(n))
print(max(n))
names.append("kranth")
print(names)
names.insert(2,"Ravi")
print(names)
names.extend(["kushi"])
print(names)
names.remove("kushi")
print(names)
nos.pop()
print(nos)
nos.clear()
print(nos)
print(nos.count(2))
n[0]=9
print(n)